/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ComparisonGroupId = IDL.Text;
export const ProductId = IDL.Text;
export const ComparisonGroup = IDL.Record({
  'id' : ComparisonGroupId,
  'productIds' : IDL.Vec(ProductId),
  'name' : IDL.Text,
});
export const CategoryId = IDL.Text;
export const Product = IDL.Record({
  'id' : ProductId,
  'title' : IDL.Text,
  'comparisonGroup' : IDL.Opt(ComparisonGroupId),
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : CategoryId,
  'rating' : IDL.Float64,
  'priceHint' : IDL.Text,
});
export const Category = IDL.Record({ 'id' : CategoryId, 'name' : IDL.Text });

export const idlService = IDL.Service({
  'getComparisonGroup' : IDL.Func(
      [ComparisonGroupId],
      [ComparisonGroup],
      ['query'],
    ),
  'getProduct' : IDL.Func([ProductId], [Product], ['query']),
  'listCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'listComparisonGroups' : IDL.Func([], [IDL.Vec(ComparisonGroup)], ['query']),
  'listProductsByCategory' : IDL.Func(
      [CategoryId],
      [IDL.Vec(Product)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ComparisonGroupId = IDL.Text;
  const ProductId = IDL.Text;
  const ComparisonGroup = IDL.Record({
    'id' : ComparisonGroupId,
    'productIds' : IDL.Vec(ProductId),
    'name' : IDL.Text,
  });
  const CategoryId = IDL.Text;
  const Product = IDL.Record({
    'id' : ProductId,
    'title' : IDL.Text,
    'comparisonGroup' : IDL.Opt(ComparisonGroupId),
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : CategoryId,
    'rating' : IDL.Float64,
    'priceHint' : IDL.Text,
  });
  const Category = IDL.Record({ 'id' : CategoryId, 'name' : IDL.Text });
  
  return IDL.Service({
    'getComparisonGroup' : IDL.Func(
        [ComparisonGroupId],
        [ComparisonGroup],
        ['query'],
      ),
    'getProduct' : IDL.Func([ProductId], [Product], ['query']),
    'listCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'listComparisonGroups' : IDL.Func(
        [],
        [IDL.Vec(ComparisonGroup)],
        ['query'],
      ),
    'listProductsByCategory' : IDL.Func(
        [CategoryId],
        [IDL.Vec(Product)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };